# Generated by Django 5.1.2 on 2024-12-01 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_contact_customer_cs_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='cs_contact',
            new_name='contact',
        ),
    ]
